# Maintainer tangfeixiong <fxtang@qingyuanos.com>
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    stackdocker.io/tags: ['cloud-native', 'message-queue']  
  labels:
    heritage: stackdocker.io
    app: gnatsd
  name: gnatsd
  namespace: stackdocker
spec:
  # replicas: 1
  # selector:
  #   matchLabels: 
  #     name: gnatsd
  #     version: '0.9.4'
  strategy: 
    type: Recreate # RollingUpdate
  template:
    metadata:
      labels:
        name: gnatsd
        version: '0.9.4'
    spec:
      containers:
      - image: tangfeixiong/gnatsd:0.9.4-c7e699a
        imagePullPolicy: IfNotPresent
        name: gnatsd
        ports:
        - containerPort: 4222
        - containerPort: 8222

