# Maintainer tangfeixiong <fxtang@qingyuanos.com>
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    stackdocker.io/tags: ['cloud-native', 'message-queue'] 
  labels:
    heritage: stackdocker.io
    name: gnatsd
  name: gnatsd
  namespace: stackdocker
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 4222
    protocol: TCP
    name: client
  - port: 8222
    protocol: TCP
    name: web
  selector:
    name: gnatsd
